### PR TITLE
SDK updates

### PR DESCRIPTION
**Pull request by Spenstar**
I needed to manually change the Android SDK version to 11.4.0 in order to get the build to work any time I re-installed the plugin. Might as well help out and update the main repo. 👍🏼

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
That's very helpful of you, thanks!

Btw, do you have any idea why you need 11.4.0 for "the build to work"? Thx!

**Comment by Spenstar** [comment]
I believe it's because of the `nativescript-geolocation` plugin. It's Google play services version is set to `11.4.0`

**Comment by EddyVerbruggen** [comment]
Ah OK. Yeah those versions are such a pita. I'll merge this soon!

**Comment by Spenstar** [comment]
I hear ya, haha. SDK version mismatches from the different plugins can be a pain.

**Comment by EddyVerbruggen** [comment]
Yeah - to that end we've added a property you can set so all plugins use the same version. Well, only a few plugins I know honor this property really. But Firebase and Geolocation are among them. So if you want, you can try:

https://github.com/NativeScript/nativescript-geolocation#version-conflicts--google-play-services

**Comment by Spenstar** [comment]
Yeah, I remember trying that a while back and still got the same error 🤔 The only way I have been able to get the Android build to be happy is to manually edit the `include.gradle` files found in the plugins.

**Comment by EddyVerbruggen** [comment]
OK. Note that the Geolocation only supports it since 4.2.0 which was released about 2 weeks ago.

Anyhow, I'll merge this soon because I like to keep up with Firebase SDK updates anyway.

**Comment by EddyVerbruggen** [comment]
Yeah I'm not too fond of that ;)

**Comment by Spenstar** [comment]
No worries 😁

**Comment by EddyVerbruggen** [comment]
Latest bump: #590.

**Pull request closed without merging**
