### PR TITLE
Added Facebook Login for Android

### LINKED ISSUE #45: Add Facebook authentication
Currently working on the iOS implementation. It's not trivial but I will pull through!

### PR DESCRIPTION
**Pull request by t-moe**
This should fix #45.

It works in my test-enviroment, but I haven't tested it with the demo app or after merge to 3.4.2. 
So please test it first before merging :). Also the docs regarding fb@android might need some polish.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Sweet! I will test this asap.

**Comment by t-moe** [comment]
Ok I've added some more bugfixes which were related.

One thing still bothers me, although it's not facebook-login related:
If you add a `AuthStateListener` it can be called multiple times per login. I'm not 100% sure but I think it's not related to this project, but rather to the firebase api on android. See https://github.com/firebase/quickstart-android/issues/80

Have you experienced this as well?

**Comment by EddyVerbruggen** [comment]
Yeah I think I have.

I tested your changes btw and it all seems to work very well, so thanks a LOT!

I will polish a few minor things after merging it.

**Comment by EddyVerbruggen** [comment]
I've also invited you to collaborate on this repo. PR's are still the way to go but you'll be able to merge them yourself, or in case of a trivial fix (code or doc) you can just push it if you like.

**Comment by t-moe** [comment]
Thanks and thanks for the invitation.
I've accepted it, but I'm not sure how much I'm going to contribute.
I'm still just playing around with NativeScript and I'm not yet sure whether to use NativeScript or Ionic for my App. I'm not happy with the stability of the NativeScript Build Process and also it's way too slow (even with  `livesync`).

**Pull request merged**
