### PR TITLE
Added option to retrieve Firebase custom claims - resolves #1008

### LINKED ISSUE #1008: Access Custom Claims On The Client - getIdTokenResult method non excistent
Hi, first o fall thanks a lot for this useful plugin.

I've been hitting my head agains the wall trying to implement accesing the custom claims from the 
client. Not sure if I've overlooked something?

Here is a link to the implementation required. 
https://firebase.google.com/docs/auth/admin/custom-claims#access_custom_claims_on_the_client

Any assistance would be greatly appreciated.

### PR DESCRIPTION
**Pull request by CaptainDingle**
Added withClaims property to getAuthToken object parameter. This adds the ability to retrieve the token plus any custom claims previously set by the Firebase admin SDK.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Looks good! Thanks for also updating the docs 👍

**Comment by Ianc22** [comment]
Hey @EddyVerbruggen, when do you think this will be avail on npm?! 📦

**Comment by EddyVerbruggen** [comment]
Yeah.. there's a feature I'm stuck with. Doing my best!

**Comment by Ianc22** [comment]
> Yeah.. there's a feature I'm stuck with. Doing my best!

Ha feel your pain... No pressure! lol Top man!

Thought it may have slipped your mind :P

**Pull request merged**
