### PR TITLE
Log complex event Analytics

### PR DESCRIPTION
**Pull request by pboulch**
Add new method : `firebase.analytics.logComplexEvent(...)` to log analytics event (works like `firebase.analytics.logEvent(...)`) but with complex event (with native type : boolean, int, float, double, string, long and with array of events, for example for the view_item_list event, an array is necessary).

### CODE REVIEW

**Comment by pboulch** [comment]
Hey ! 
Is it possible to merge this PR please ? I use this feature regularly and it works fine.

Thanks !

**Comment by EddyVerbruggen** [comment]
This looks amazing, let me merge and test it. I'm planning to release 7.5.0 soon and this will be part of it. Thank you for also updating the demo app!

**Comment by Ianc22** [comment]
Hey again Eddy! On to the next feature of the plugin! Just came across this issue, found the **logComplexEvent()** method by looking at the code, here's a reminder for you to update the documentation :)

**Comment by EddyVerbruggen** [comment]
@Ianc22 lol 😊 - done.

**Pull request merged**
