### PR TITLE
fix: google-utilities cocoapods dependency

### PR DESCRIPTION
**Pull request by jnorkus**
#924

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi, thanks for the PR! Unfortunately, I can't simply bump the Pod version because usually, things have changed in the native classes so there's a bit more work to be done (and thorough testing!).

Perhaps it's easier / safer to apply the temporary fix suggested [here](https://github.com/firebase/firebase-ios-sdk/issues/1845#issuecomment-422894455) and remove it once we bump to 5.8.1.

Btw, the actual file that needs to be changed in publish/scripts/installer.js. I know that's not too clear, but folks hardly PR the install script anyway.

**Comment by EddyVerbruggen** [comment]
FYI I'm going to add that temp fix to plugin version 7.1.0, even though I have never been able to reproduce the issue in #924.

**Comment by Julio77** [comment]
> Hi, thanks for the PR! Unfortunately, I can't simply bump the Pod version because usually, things have changed in the native classes so there's a bit more work to be done (and thorough testing!). And this version seems to have massive compile issues with Xcode 10 with NativeScript.
> 
> Perhaps it's easier / safer to apply the temporary fix suggested [here](https://github.com/firebase/firebase-ios-sdk/issues/1845#issuecomment-422894455) and remove it once we bump to 5.8.1.
> 
> Btw, the actual file that needs to be changed in publish/scripts/installer.js. I know that's not too clear, but folks hardly PR the install script anyway.

Temporary solution

Open in your nativescript project
Platforms/ios/Podfile

Add the line `pod 'GoogleUtilities', '5.2.3'`

and try to compile the project again.

**Comment by EddyVerbruggen** [comment]
@Julio77 that's already part of the latest released plugin version ;)

**Comment by Julio77** [comment]
> @Julio77 that's already part of the latest released plugin version ;)

i re-install plugin and try, and again is broken.
i uninstall plugin `tns plugin remove nativescript-plugin-firebase`
and run `tns plugin add nativescript-plugin-firebase`

can't compile

thanks

**Comment by EddyVerbruggen** [comment]
Remove the platforms folder.

**Comment by prabudevarrajan** [comment]
Hi @EddyVerbruggen, in my project I added the tns add plugin nativescript-plugin-firebase and I am getting the following error. My Xcode version is "9.4.1 (9F2000)" 

package.json
```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.xyz.xyz",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "angular2-moment": "^1.7.0",
    "nativescript-angular": "^6.1.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "tns-core-modules": "^4.2.0",
    "zone.js": "^0.8.26"
}
}
```

```
$ tns debug ios
..
...
...

[!] CocoaPods could not find compatible versions for pod "GoogleUtilities":
  In Podfile:
    GoogleUtilities (= 5.2.3)

None of your spec sources contain a spec satisfying the dependency: `GoogleUtilities (= 5.2.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

```

**Comment by prabudevarrajan** [comment]
hi @EddyVerbruggen , i did $ pod repo update and after that the above error is gone

**Pull request closed without merging**
