### PR TITLE
Allow disk persistence

### PR DESCRIPTION
**Pull request by triniwiz**
```js
firebase.init({
        url: 'https://yourfbdb.firebaseio.com',
        persist: true
    })
```

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hey @triniwiz I like this feature but your PR changes the indents from 2 to 4 spaces so it's very hard to tell what the change is exactly (and I like 2 space indents). Can you please update your PR?

Cheers,
Eddy

**Comment by EddyVerbruggen** [comment]
Hi @triniwiz much better, thanks, but it looks like you've added Java code to the iOS firebase file. For example: https://github.com/triniwiz/nativescript-plugin-firebase/blob/master/firebase.ios.js#L5

**Comment by triniwiz** [comment]
@EddyVerbruggen sorry about that copy and paste error on my end :confused:

**Comment by EddyVerbruggen** [comment]
No worries that's what code reviews are for ;)

I'll do a manual merge later today as it's not possible to auto-merge it according to GitHub.

**Comment by EddyVerbruggen** [comment]
Merged in 2.1.8, thanks again.

**Pull request closed without merging**
