### PR TITLE
Adding additionalUserInfo and metadata to sign in response #763

### PR DESCRIPTION
**Pull request by RaphaelJenni**
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/763

### CODE REVIEW

**Comment by RaphaelJenni** [comment]
@EddyVerbruggen any news?

**Comment by EddyVerbruggen** [comment]
This is not the only thing in my life.. I can't just drop everything on the spot.

**Comment by RaphaelJenni** [comment]
I didn't mean to insult you, was just a question as I haven't heard anything from you.

**Comment by EddyVerbruggen** [comment]
I'm not insulted in any way, it's just that this PR was opened 19 hours ago and it's part of a pile of millions of issues I'm supposed to attend to.

**Comment by EddyVerbruggen** [comment]
I'll try doing it soon. It needs testing on both platforms, I'll add it to the demo app and the readme (unless you've already documented the changes). Then test other parts of the release and publish to npm.

**Comment by RaphaelJenni** [comment]
Ok, perfect, thanks.
I tested it on Android and iOS (emulator and device). The Readme isn't updated.

**Comment by EddyVerbruggen** [comment]
Great work, I've reviewed it and make a few small tweaks and added docs. About to release 6.3.0.

**Pull request merged**
