### PR TITLE
Adding ability to (un/)subscribe to topics at firebase

### PR DESCRIPTION
**Pull request by markosko**
Tested and works.
Have done only for android as i don't have Mac so can't test iOS but it's almost same way at iOS part.

### CODE REVIEW

**Comment by rcluan** [comment]
Hi, @markosko . In your unsubscribe method shouldn't be unsubscribeFromTopic() instead of unsubscribeToTopic() when using com.google.firebase.messaging.FirebaseMessaging.getInstance()?

**Comment by markosko** [comment]
Quite possible as i copied some things between lines :D i will change it :)

**Comment by rcluan** [comment]
I've tested and it's working like a charm both subscribe and unsubscribe methods. =D well done

**Comment by EddyVerbruggen** [comment]
Cool! Looks good to me as well. Let's merge this, or do you want to add a bit of documentation first? I can do that if you don't feel like it ;)

**Comment by markosko** [comment]
Dont mind to do some docs, but can someone later pull up ios side so that we have both platforms in sync ? :) tommorow I can add docs

**Comment by EddyVerbruggen** [comment]
Sweet, I'll take care of iOS as I'm planning on doing some maintenance work for this plugin in the next few days anyway.

**Comment by markosko** [comment]
and add it to messaging docs part right ?

**Comment by markosko** [comment]
and one more thing @EddyVerbruggen should I add info to docs about only android will be temporary available or no need for that ?

**Comment by EddyVerbruggen** [comment]
@markosko I'll look at it now and take care of any docs changes. Thanks!!

**Pull request merged**
