### PR TITLE
Basic integration of Crashlytics for iOS...

### PR DESCRIPTION
**Pull request by DickSmith**
...including automatic dSYM uploads. Based on @hypery2k 's `nativescript-fabric` plugin.

Since it is only for iOS right now, both original Firebase `crash_reporting` and `crashlytics` can be enabled. If `crashlytics` is enabled, then `crash_reporting` is disabled for iOS, but still enabled for Android.
I prioritized Crashlytics for iOS since the original `crash_reporting` works well enough for Android issues (even with uglify on, but no obfuscation on proguard), but for iOS without dSYM it's almost impossible to decode most of them. The Crashlytics for Firebase offered the easiest solution for automatic dSYM uploading. For Crashlytics dSYM to be properly generated, bitcode must be disabled, which is done via the podfile for all targets.

I have this running in Prod with 30,000+ daily users.

TODOs: implement Android; integrate custom logging

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi @DickSmith this is awesome!

Do you feel like this is ready to be merged? If so, I'll test it and merge to master so we can ship it with release 5.0.0. It will take a little while to get all tasks for 5.0.0 completed, so there is no rush or anything.

Thanks,
Eddy

**Comment by hypery2k** [comment]
@DickSmith this looks great. I could help on this. I currently working on the Android part on my [plugin](https://github.com/hypery2k/nativescript-fabric). Should me maybe merge our work somehow?
@EddyVerbruggen Not sure if it would be feature to make a branch directly on your plugin and work together there. What do you think? 
I could break CI builds to the table, also with snapshots builds ;)

**Comment by EddyVerbruggen** [comment]
If there's anything I can do to help let me know. But perhaps it's easiest to push changes to Dick's fork so all of it ends up in this PR?

**Comment by DickSmith** [comment]
@EddyVerbruggen Yes it appears to be very stable, other than no ability to add the custom logs yet (https://firebase.google.com/docs/crashlytics/customize-crash-reports), which I hadn't been using yet with the original `crash_reporting`, so haven't explored much yet. Other than that it is currently building correctly both locally (debug) and on my TravisCI (release with webpack/AoT/uglify; including the automatic dSYM upload), and I currently have 9000 iOS users already using the version with Crashlytics since I released it yesterday with no issues (other than the preexisting crashes that I can now actually make sense of with the symbols 😁 ). Will probably have several thousand more on it by the end of the day too.

@EddyVerbruggen @hypery2k I'm open to whatever works best for you guys. This would have definitely been far more difficult without being able to "borrow" from @hypery2k 's plugin. 😀

**Comment by hypery2k** [comment]
you can take a look at my android branch [here](https://github.com/hypery2k/nativescript-fabric/tree/bugfix/android)
But I'm currently facing some issues:
```
12-15 12:52:27.920  2827  2827 I TNS.Native: NativeScript Runtime Version 3.3.1, commit 368c29d75ca1cb632aa1efd8f822bacdd3c4da41
12-15 12:52:27.920  2827  2827 D TNS.Native: JNI_ONLoad
12-15 12:52:27.920  2827  2827 D TNS.Native: JNI_ONLoad END
12-15 12:52:27.945  1961  2128 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f8bb267a4a0
12-15 12:52:28.059  1584  1584 I free_storage_changed: 1709887488
12-15 12:52:28.404  1584  1959 I dvm_lock_sample: [system_server,1,Binder_6,51,WindowManagerService.java,11874,WindowAnimator.java,121,10]
12-15 12:52:28.525  1232  1232 I sf_frame_dur: [com.android.launcher3/com.android.launcher3.Launcher,0,1,6,2,1,2,7]
12-15 12:52:28.526  2801  2815 E QueryController: Got null root node from accessibility - Retrying...
12-15 12:52:28.778  2801  2815 E QueryController: Got null root node from accessibility - Retrying...
12-15 12:52:28.872  2827  2827 D TNS.Native: Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found
12-15 12:52:28.916  2827  2827 D TNS.Native: V8 version 5.5.372.32
12-15 12:52:29.029  2801  2815 E QueryController: Got null root node from accessibility - Retrying...
12-15 12:52:29.052  1247  1247 I SELinux : SELinux: Loaded file_contexts contexts from /file_contexts.
12-15 12:52:29.052  1247  1247 I auditd  : SELinux: Loaded file_contexts contexts from /file_contexts.
12-15 12:52:29.099  1247  1247 E DEBUG   : AM write failed: Broken pipe
12-15 12:52:29.100  1584  2848 I am_crash: [1584,0,org.nativescript.demo,950582854,Native crash,Aborted,unknown,0]
12-15 12:52:29.100  1584  1601 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
12-15 12:52:29.101  1584  2848 W ActivityManager:   Force finishing activity org.nativescript.demo/com.tns.NativeScriptActivity
12-15 12:52:29.101  1584  2848 I am_finish_activity: [0,110625689,10,org.nativescript.demo/com.tns.NativeScriptActivity,force-crash]
12-15 12:52:29.153  1263  1263 I Zygote  : Process 2827 exited due to signal (6)
12-15 12:52:29.279  2801  2815 E QueryController: Cannot proceed when root node is null. Aborted search
12-15 12:52:29.280  2801  2815 E QueryController: Got null root node from accessibility - Retrying...
12-15 12:52:29.402  1584  2848 I WindowManager: Screenshot max retries 4 of Token{128565e ActivityRecord{6980399 u0 org.nativescript.demo/com.tns.NativeScriptActivity t10 f}} appWin=Window{36f33a4 u0 Starting org.nativescript.demo} drawState=4
12-15 12:52:29.402  1584  2848 I am_pause_activity: [0,110625689,org.nativescript.demo/com.tns.NativeScriptActivity]
12-15 12:52:29.403  1584  2848 W ActivityManager: Exception thrown during pause
12-15 12:52:29.403  1584  2848 W ActivityManager: android.os.DeadObjectException
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
12-15 12:52:29.403  1584  2848 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
12-15 12:52:29.404  1584  2848 I am_home_stack_moved: [0,1,0,0,noMoreActivities setFocusedActivity]
12-15 12:52:29.404  1584  2848 I wm_task_moved: [9,1,0]
```

you try yourself with my demo app [here](https://github.com/hypery2k/nativescript-fabric/tree/bugfix/android/demo) and adding `npm i nativescript-fabric@1.0.6-bugfix-android-23 --E --S`

```
After adding the plugin to my demo project i had to do an additional `tns build android`, otherwise the app crashes, see here: https://github.com/NativeScript/android-runtime/issues/358#issuecomment-352002965

**Comment by DickSmith** [comment]
@EddyVerbruggen @hypery2k
K, so I finally got this working on Android; was a bit more complicated since it requires some bleeding edge as described [here](urlhttps://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/549/files#diff-b01fbdc5453c76846434fd1ae647d7e0R495):
```
// Crashlytics requires Firebase >= 11.8.0
// Firebase 11.8.0 requires google-services plugin >= 3.1.2
// google-services plugin 3.1.2 requires gradle-plugin >= 3.0.1
// gradle-plugin 3.0.1 requires buildToolsVersion >=26.0.3
```
Tested with both PAN-demo and ng-demo (with and without Crashlytics enabled), as well as in my own ns+ng app.

Same as iOS before, if `crashlytics` is enabled in the config then the original `crash_reporting` is disabled.

However, getting the same issue as @hypery2k , somewhat different output, but second build works while first doesn't.

**Comment by hypery2k** [comment]
I'm waiting for feedback from @plamen5kov, see [here](https://github.com/NativeScript/android-runtime/issues/358#issuecomment-354258242)

@DickSmith: Maybe this helps here, too

**Comment by manojdcoder** [comment]
Thank you guys for making this. So it should be functional now with TNS >= 3.4?

**Comment by hypery2k** [comment]
no, it's currently having issues, see [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/549#issuecomment-354984462). I can not solve the class path issue for now. So currently not able to fix

**Comment by DickSmith** [comment]
@EddyVerbruggen @hypery2k 

So after trying dozens of different combinations over the last few weeks I've decided to hold off on the Android integration. There still seems to be much more in flux for the Android integration of Crashlytics than there was for iOS (which seems strange it being Google and all, but not so strange... it being Google and all :D ).

I could get it to build with various combinations of tools, configurations, etc, but could never get it to reliably launch and report to Crashlytics. The main problem being that the docs insist that `google-services` plugin was required to be 3.1.2+, which then needed the latest `build:gradle:3.0.1`, which then needed some adjustments to the `app/build.gradle` which you can see before the revert [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/549/commits/d25fc6a281d68fd97e53748858d5e0f7ffa8e9e4), but then the new `google-services` plugin seemed to have a hard time with the way the {N} template uses variants/flavors/dimensions which I couldn't find a straight-forward solution to.

So I pulled out those changes and just set it back to being iOS only for this PR, which does work well, and I used in production with several hundred thousand users during the Christmas season (my main app is a Christmas app).

There's also far more advantages to having Crashlytics for iOS, since the dSYMs are auto-uploaded at build-time. If anything, there is less advantage using Crashlytics with Android currently since you don't get the additional analytics logging added to the crash reports like you do with the original Firebase Crash Reporting, which does a good job of reporting both Java and JS errors already.

So for now I guess I'll just leave this PR at its original scope for adding Crashlytics for iOS for now.

I'll look into Android again in a month or so when Google has solidified it a bit more. And also will be looking into a way of getting more logging for the Crashlytics portions as well.

**Comment by TheOnlyMatt** [comment]
Hi !
If I have correctly understood, to sum up, right now it is better to use Firebase Crash Reporting over Crashlytics, because it works correctly on both platforms that's it ?

**Comment by DickSmith** [comment]
@TheOnlyMatt 
For Android, yes, Firebase Crashlytics has more disadvantages than Firebase Crash Reporting.

For iOS however, Firebase Crash Reporting has no easy way to automatically upload the dSYMS at buildtime and must be done manually, which doesn't work easily if you're using a CI build machine. These changes allow the dSYMs to be uploaded any time a build is run (locally or remotely) for Crashlytics. With my current set up I enable both Crashlytics and Crash Reporting in my config file, and if both are enabled it enables Crash Reporting for Android and only Crashlytics for iOS.

I am also looking at ways to add more JS crash log info to the iOS Crashlytics this week. Currently, on Android, Crash Reporter shows both Java errors and JS errors easily, but on iOS, and even with the dSYMs, both Crashlytics and Crash Reporting will only give the Native error stack, which if the issue was caused by a JS execution, will just show that something failed in the JS.

**Comment by TheOnlyMatt** [comment]
Okay thanks for the answer !

For my part, in a first time I chose to use only Crash Reporter to have a code easier to maintain, but when Crashlytics will be production ready on both platform, I will try to migrate on this system.

Anyway, I can confirm that I had an iOS crash reported, indeed the report is very messy. It is clearly useless to me.
It looks like more as a hardware exception than a software one, I don't even know on which screen the error has occured.

At least, it enables to make get an idea about the app stability.

**Comment by DickSmith** [comment]
@EddyVerbruggen 

I just added the improved logging to this, which allowed me to quickly identify a crash that was occurring in `tns-core-modules`: https://github.com/NativeScript/NativeScript/pull/5475.

Additionally, Firebase/Crashlytics is now also including the analytics logs like the old Crash Reporting did, so it will have both the user path via the trackers as well as the JS errors that occur.

**Comment by EddyVerbruggen** [comment]
@DickSmith Yeah nasty issue that one.

Awesome that this will actually report an issue like that!

So you think it's ready for prime time?

**Comment by hypery2k** [comment]
@DickSmith So is currently iOS and Android working for you?

I still struggling on my nativescript-fabric plugin with the Android Build and I currently think I should quit my plugin in favour to integrate all in the firebase plugin

**Comment by sitefinitysteve** [comment]
How much of this changes with the out of beta announcement? https://firebase.googleblog.com/2018/03/firebase-crashlytics-graduates-from-beta.html

**Comment by DickSmith** [comment]
@EddyVerbruggen 
Yes. The core of this (SDK integration and the dSYM upload) has been stable since end of November in my Christmas app (PNP 2017 Portable North Pole, on App/Play Stores). And the additional logging has been in release for about 2-3 weeks now (about a million users in December and still a few thousand a month, even now).

@hypery2k 
So I haven't looked at Android again since end of January, so I don't know if the situation has improved or not, but with the official announcement that @sitefinitysteve mentioned I guess I'll give it another look in the coming weeks. It also looks like with that official announcement that the Firebase Console UI is now pushing hard for people to transition from the old Crash Reporting to Firebase/Crashlytics now. They don't give a timeline for when they plan to remove the old Crash Reporting, so I would be guessing maybe at least a few months, but can't be certain. When I look at the old Fabric/Crashlytics dashboard (my old non-{N} apps were using Fabric/Crashlytics directly), I don't see a mention of when they plan to retire it, but I'm guessing it will be at some time in the next few months as well?

@sitefinitysteve 
It appears that my current iOS implementation is still fully supported, including the additional analytics integration which I've been seeing for a few weeks now. From what I can see there haven't been any changes to the documentation for Firebase/Crashlytics that would affect what I've done (other than it mentioning specific versions to pin to in the CocoaPod now, so it'd be a question for @EddyVerbruggen about if we want to pin these pod versions or not per his usual preferences there.)

@EddyVerbruggen 
In short, this PR is stable and _well proven_ for enabling Crashlytics on iOS, so should be good to get merged and I'll make another PR once I figure out the Android situation now that the disadvantage of Firebase/Crashlytics not including the analytics has been resolved with the official release.

I'll post another PR in the coming weeks that will include the full removal of the old `crash_reporting` stuff (while maintaining backward compatibility with the `firebase.nativescript.json` so that having either `crashlytics` or `crash_reporting` set to true will enable Crashlytics for both iOS and Android).

I still have a branch with the Android changes I had been working on, so I should be able to pick up where I left off easily enough, but it may still take some massaging to get it to work. I am also not sure if the changes coming in `{N}` 4.0 will make this easier or harder as last I checked some of the big changes to the `tns-android` template project seemed to affect the way some of this will need to work, especially in the `*.gradle` files. So the PR I end up making may only be compatible with one or the other for now (depending on what I find).

If you have any questions, feel free to send me a message on the {N} Slack, where my username is also `dicksmith` .

**Comment by DickSmith** [comment]
@EddyVerbruggen 
It also looks like this commit ended up on this PR which fixes an issue I was seeing in Android: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/549/commits/bb5bb5e25bc4cdf53838241134d47ccc25b1af81

If you want I can revert it and submit it in another PR, or leave it.

**Comment by EddyVerbruggen** [comment]
@DickSmith You can leave it in here, I'll be merging it as soon as I've finished a few other things. Won't be too long. Thanks so much for your work and perseverance!

**Comment by hypery2k** [comment]
did you have a preview build of the plugin? I could verify it in our beta test setup

**Comment by DickSmith** [comment]
@EddyVerbruggen 
If the crash log has stack has stuff like
`NativeScript
NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool) + 1784`
Then the dSym is successful, otherwise you have stuff like:
Otherwise you would just see anonymous memory addresses. Stuff like `NativeScript+88499` or whatever... might not even see the `NativeScript` part.

@hypery2k If you want I could send you the `.tgz` I've been using either via Slack or email.

**Comment by EddyVerbruggen** [comment]
@DickSmith  Yep, I see the former so it's working 😍

@hypery2k I was just chatting with @DickSmith on Slack while narrowing down what causes the crash on Android in both your Fabric plugin and this one (as I was working on adding the Android side of Crsahlytics to Firebase today).

The good news: found it! 🎉

The bad news: both our plugins need an ugly build step to copy the Android runtime `metadata` (3 `.dat` files) from the src folder (the highlighted one at the bottom of the screenshot) to the build folder (the one at the top) because somehow the NativeScript build system and Crashlytics bite each other (Crashlytics writes a file called `crashlytics-build.properties` (also highlighted) to the same folder as where the metadata needs to be copied to).

I can't tell for sure this is the cause, I only see the symptom. But that symptom will be cured by a build step which I can also PR to the Fabric plugin if you like.

screen shot 2018-04-24 at 21 08 19

**Comment by hypery2k** [comment]
great for the hint. Feel free to send a PR in this [branch](https://github.com/hypery2k/nativescript-fabric/tree/bugfix/114_app_crash). Glad for your support

**Pull request merged**
