### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by blagoev**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hey @blagoev would that make [this manual bit](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#android) obsolete? If so, then ❤️  ❤️  ❤️

**Comment by blagoev** [comment]
no that fixes our CI build since they changed how Firebase should be referenced. I guess the manual bit is still required

**Comment by blagoev** [comment]
we should merge this since right now the CI is reconfigured to use the forked repo

**Comment by EddyVerbruggen** [comment]
👍

**Comment by blagoev** [comment]
@EddyVerbruggen : 10x. Can you publish this to npm since it turns out our verified plugins CI build is using that version and now it is taking the latest from npm which does not have the fix.

**Comment by EddyVerbruggen** [comment]
Alright, will do in a few hours (not at my laptop atm, sorry)

**Comment by EddyVerbruggen** [comment]
OK, done.

**Pull request merged**
