### PR TITLE
Redo for separation of environments

### LINKED ISSUE #905: Separation of Environments
Greetings,

Recently I saw a new section named "Separation of Environments" on the main plugin documentation, I tried adding it to my project but wasn't able to make it work.

Reviewing the plugin's history this functionality was removed from the code.

Is there another way to have separate environments on my project?

Thanks in advance.

### PR DESCRIPTION
**Pull request by abhayastudios**
Redo of #836. Closes #905.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Oh, hang on, you're altering the postinstall script - this gets generated on build from [publish/scripts/installer.js](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/publish/scripts/installer.js), so actually *that one* needs to be changed.

You may wondering why the h*** I commit the (generated) postinstall script, but that's needed for CI and tests.

Sorry if that's not clear, and also sorry I did not notice this the previous time around.

Anyway, I'll merge this PR and apply the changes to the install script myself. Thanks!

**Comment by rgomezu** [comment]
Hi thanks for your help, Is this ready to use? I tried installing the plugin again, but the post install script it's not updated with this changes.

**Comment by EddyVerbruggen** [comment]
It's not released yet. Check the milestone on the right. It says 7.0.0, and the npm version is a bit lower. Give me a day or two..

**Comment by rgomezu** [comment]
Oh ok, sure, thanks for the update.

**Pull request merged**
