### PR TITLE
Suggestion for documentation of functions' region feature

### PR DESCRIPTION
**Pull request by siavee**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Awesome, thank you!

**Comment by EddyVerbruggen** [comment]
Note that this feature will be part of the soon-to-be-released 10.0.0 version.

**Comment by siavee** [comment]
You mean the function regions feature? Awesome! Right now I'm using the forked version.

**Comment by EddyVerbruggen** [comment]
Yep. It will land on npm today or tomorrow.. I'm currently working like a madman to test all new and changes bits 🤪

**Comment by siavee** [comment]
Super awesome! Can't wait to get my hands on it 😆

**Pull request merged**
