### PR TITLE
[Android] Added support to create custom prompt or ui for phone verification code 

### PR DESCRIPTION
**Pull request by rmn81**
**[Android]** Added support to create custom prompt or UI for phone verification code.

Didn't added for iOS due to lack of testing device. but the same can also be done for iOS.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Very cool! Would you mind adding this to the authentication readme as well, along with a little example so folks will know how to use it?

**Comment by ramkaranyadav18** [comment]
> Very cool! Would you mind adding this to the authentication readme as well, along with a little example so folks will know how to use it?

OK I will add in a day or two

**Comment by danielorihuela** [comment]
That feature is really interesting! Are you planning on reviewing and merging it soon? @EddyVerbruggen

**Comment by linuxsimba** [comment]
@rmn81 not sure if you have the code for IOS but I'm using this in my project. 

```
diff --git a/src/firebase.android.ts b/src/firebase.android.ts
index cc352ba..4aa6d2c 100755
--- a/src/firebase.android.ts
+++ b/src/firebase.android.ts
@@ -1156,7 +1156,7 @@ firebase.login = arg => {
             setTimeout(() => {
               if (firebase._verifyPhoneNumberInProgress) {
                 firebase._verifyPhoneNumberInProgress = false;
-                firebase.requestPhoneAuthVerificationCode(userResponse => {
+                let onUserResponse = (userResponse) => {
                   if (userResponse === undefined && firebase.reject) {
                     firebase.reject("Prompt was canceled");
                     return;
@@ -1169,7 +1169,12 @@ firebase.login = arg => {
                   } else {
                     user.linkWithCredential(authCredential).addOnCompleteListener(onCompleteListener);
                   }
-                }, arg.phoneOptions.verificationPrompt);
+                }
+                if (arg.phoneOptions.onRequestPhoneAuthVerificationCode) {
+                  arg.phoneOptions.onRequestPhoneAuthVerificationCode(onUserResponse);
+                } else {
+                  firebase.requestPhoneAuthVerificationCode(onUserResponse, arg.phoneOptions.verificationPrompt);
+                }
               }
             }, 3000);
           }
diff --git a/src/firebase.ios.ts b/src/firebase.ios.ts
index a5dac1a..5407def 100755
--- a/src/firebase.ios.ts
+++ b/src/firebase.ios.ts
@@ -1016,13 +1016,14 @@ firebase.login = arg => {
           return;
         }
 
+
         FIRPhoneAuthProvider.provider().verifyPhoneNumberUIDelegateCompletion(arg.phoneOptions.phoneNumber, null, (verificationID: string, error: NSError) => {
           if (error) {
             reject(error.localizedDescription);
             return;
           }
 
-          firebase.requestPhoneAuthVerificationCode(userResponse => {
+         let onUserResponse = (userResponse) => {
             if (userResponse === undefined) {
               reject("Prompt was canceled");
               return;
@@ -1042,7 +1043,14 @@ firebase.login = arg => {
             } else {
               firebase.fAuth.signInWithCredentialCompletion(fIRAuthCredential, onCompletionWithAuthResult);
             }
-          }, arg.phoneOptions.verificationPrompt);
+          };
+
+          if (arg.phoneOptions.onRequestPhoneAuthVerificationCode) {
+            arg.phoneOptions.onRequestPhoneAuthVerificationCode(onUserResponse);
+          } else {
+            firebase.requestPhoneAuthVerificationCode(onUserResponse, arg.phoneOptions.verificationPrompt)
+          }
+
         });
 
       } else if (arg.type === firebase.LoginType.CUSTOM) {
~

```

**Pull request closed without merging**
